[project]
name = "socca"
version = "0.1.0"
description = "Source Characterization using a Composable Analysis"
authors = [{name="Luca Di Mascolo",email="lucadimascolo@gmail.com"}]
license = {"file" = "LICENSE"}
requires-python = ">=3.9"

dependencies = [
    "matplotlib",
    "numpy",
    "scipy",
    "astropy",
    "pyregion",
    "reproject",
    "jax",
    "jaxlib",
    "quadax",
    "numpyro",
    "dynesty",
    "nautilus-sampler",
    "pocomc",
    "corner",
    "dill",
    "h5py"
]

[tool.setuptools.packages.find]
include = ["socca*"]
exclude = ["input*"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"